api_platform:
    title: 'Symfony REST API'
    description: 'A Symfony API to customer fidelity.'
    version: '2.6.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header
